[package]
name = "agent-flow"
version = "0.1.0"
edition = "2024"

[dependencies]
# Router
tokio = { version= "1.53.1", features = ["full"]}

# Json
serde = {version = "1.0.229", features = ["derive"]}
serde_json = "1.0.151"
serde_with = "3.21.0"

# Web
axum = {version= "0.8.9", features=[]}
axum-macros = "0.5.1"

tower-http = {version = "0.7.0", features =["fs"]}
tower-cookies = "0.11.0"


# Misc.
uuid = { version = "1.24.0", features = ["v4", "fast-rng"] }
lazy-regex = "3.6.0"
async-trait = "0.1.91"
strum_macros = "0.28.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
derive_more = { version = "2.1.1", features = ["from","display"] }


[dev-dependencies]
httpc-test = "0.1.10"
anyhow = "1.0.104"